export { default as Navbar } from './Navbar/Navbar'
export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Carousel } from './Carousel/Carousel'
export { default as HrSlider } from './HrSlider/HrSlider'